api/urls.py
from django.urls import path
from rest_framework import routers

from api.views import TokenAuthenticationViewSet, UsersViewSet, RestaurantsViewSet, CartViewSet, \
    FoodItemsViewSet, ProfileViewSet, CustomerOrdersViewSet, VendorOrdersViewSet

router = routers.SimpleRouter()
router.register(prefix='auth', viewset=TokenAuthenticationViewSet, basename='auth')
router.register(prefix='users', viewset=UsersViewSet, basename='users')
router.register(prefix='restaurants', viewset=RestaurantsViewSet, basename='restaurants')
router.register(prefix='fooditems', viewset=FoodItemsViewSet, basename='fooditems')


customer_urlpaterns = [
    path('customers/<str:username>/orders/', CustomerOrdersViewSet.as_view({'get': 'list'})),
    path('customers/<str:username>/orders/<str:order_number>/', CustomerOrdersViewSet.as_view({'get': 'retrieve'})),
    path('customers/<str:username>/profile/', ProfileViewSet.as_view(
            {'get': 'profile', 'put': 'profile', 'patch': 'profile'})
         ),
    path('customers/<str:username>/my_cart/', CartViewSet.as_view({'get': 'list'})),
    path('customers/<str:username>/my_cart/<int:pk>/', CartViewSet.as_view(
        {'get': 'retrieve', 'delete': 'destroy', 'put': 'update'})
         ),
]

vendor_urlpatterns = [
    path('vendors/<str:vendor_slug>/orders/', VendorOrdersViewSet.as_view({'get': 'list'})),
    path('vendors/<str:vendor_slug>/orders/<str:order_number>/', VendorOrdersViewSet.as_view({'get': 'retrieve'})),
    path('vendors/<str:vendor_slug>/profile/', ProfileViewSet.as_view(
        {'get': 'profile', 'put': 'profile', 'patch': 'profile'})
         ),
    ]

urlpatterns = [
    ]

urlpatterns += router.urls
urlpatterns.extend(customer_urlpaterns)
urlpatterns.extend(vendor_urlpatterns)

food_marketplace/urls.py
from django.contrib import admin
from django.urls import path, include

from food_marketplace import views
from django.conf.urls.static import static
from django.conf import settings
from marketplace import views as marketplace_views

urlpatterns = [
    path('admin/', admin.site.urls, name=admin),
    path('', views.home, name='home'),
    path('', include('accounts.urls')),
    path('api/', include('api.urls')),
    path('marketplace/', include('marketplace.urls')),
    path('cart/', marketplace_views.cart, name='cart'),

    path('search/', marketplace_views.search, name='search'),

    path('checkout/', marketplace_views.checkout, name='checkout'),

    path('orders/', include('orders.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.contrib.gis.db import models as gismodels
from django.contrib.gis.geos import Point


# Create your models here.
class UserManager(BaseUserManager):
    def create_user(self, first_name, last_name, username, email, password=None):
        if not email:
            raise ValueError('User must have an email address')

        if not username:
            raise ValueError('User must have an username')

        user = self.model(
            email=self.normalize_email(email),
            username=username,
            first_name=first_name,
            last_name=last_name,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, first_name, last_name, username, email, password=None):
        user = self.create_user(first_name=first_name, last_name=last_name, username=username,
                                email=self.normalize_email(email), password=password)
        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superadmin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    VENDOR = 1
    CUSTOMER = 2

    ROLE_CHOICE = (
        (VENDOR, 'Vendor'),
        (CUSTOMER, 'Customer'),
    )
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    phone_number = models.CharField(max_length=12, blank=True)
    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICE, blank=True, null=True)

    # required fields
    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_superadmin = models.BooleanField(default=False)
    is_subscribed = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    objects = UserManager()

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True


class UserProfile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    profile_picture = models.ImageField(upload_to='users/profile_picture')
    cover_photo = models.ImageField(upload_to='users/cover_photos', default="/default_images/default_cover_photo.png")
    address = models.CharField(max_length=250, blank=True, null=True)
    country = models.CharField(max_length=15, blank=True, null=True)
    state = models.CharField(max_length=15, blank=True, null=True)
    city = models.CharField(max_length=15, blank=True, null=True)
    pin_code = models.CharField(max_length=6, blank=True, null=True)
    latitude = models.CharField(max_length=20, blank=True, null=True)
    longitude = models.CharField(max_length=20, blank=True, null=True)

    location = gismodels.PointField(blank=True, null=True, srid=4326)

    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.email

    def save(self, *args, **kwargs):
        if self.longitude and self.latitude:
            self.location = Point(float(self.longitude), float(self.latitude))

        return super(UserProfile, self).save(*args, **kwargs)

orders/models.py
import datetime

from django.db import models
from django.db.models import QuerySet

from accounts.models import User
from menu.models import FoodItem
from vendors.models import Vendor

request_object = None


class Payment(models.Model):
    PAYMENT_METHOD = (
        ('PayPal', 'PayPal'),
        # ('Cash', 'Cash'),
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    transaction_id = models.CharField(max_length=100)
    payment_method = models.CharField(choices=PAYMENT_METHOD, max_length=100)
    amount = models.CharField(max_length=10)
    status = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.transaction_id


class OrderQuerySet(models.QuerySet):
    def paid_orders_by_user(self, user):
        return self.filter(user=user, is_ordered=True)

    def current_month_orders_by_vendor(self, vendor_pk, today):
        return Order.objects.filter(vendor__in=[vendor_pk],
                                    created_at__month=today.month,
                                    created_at__year=today.year,
                                    is_ordered=True)

    def current_day_orders_by_vendor(self, vendor_pk, today):
        return Order.objects.filter(vendor__in=[vendor_pk],
                                    created_at__day=today.day,
                                    created_at__month=today.month,
                                    created_at__year=today.year,
                                    is_ordered=True)


class OrderManager(models.Manager):
    def get_queryset(self):
        return OrderQuerySet(self.model, using=self._db)

    def get_total_revenue(self, orders: QuerySet, vendor_id: int) -> float:
        revenue = 0
        for order in orders:
            revenue += order.get_total_by_vendor(vendor_id=vendor_id)
        return round(revenue, 2)

    def paid_orders_by_user(self, user):
        return self.get_queryset().paid_orders_by_user(user)

    def current_month_orders_by_vendor(self, vendor_pk: int, today: datetime.datetime):
        return self.get_queryset().current_month_orders_by_vendor(vendor_pk, today)

    def current_day_orders_by_vendor(self, vendor_pk: int, today: datetime.datetime):
        return self.get_queryset().current_day_orders_by_vendor(vendor_pk, today)


class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Completed', 'Completed')
    )
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, null=True, blank=True)
    vendor = models.ManyToManyField(Vendor, blank=True)
    order_number = models.CharField(max_length=28)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=15)
    email = models.EmailField(max_length=50)
    address = models.CharField(max_length=200)
    country = models.CharField(max_length=15, blank=True)
    state = models.CharField(max_length=15, blank=True)
    city = models.CharField(max_length=50)
    pin_code = models.CharField(max_length=10, blank=True, null=True)
    total = models.FloatField(max_length=10)
    total_data = models.JSONField(blank=True, null=True)
    tax_data = models.JSONField(blank=True, help_text="Data format: {'tax_ty}")
    total_tax = models.FloatField()
    payment_method = models.CharField(max_length=25)
    status = models.CharField(choices=STATUS, default='New')
    is_ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = OrderManager()

    @property
    def name(self):
        return f'{self.first_name} {self.last_name}'

    def order_placed_to(self):
        return ', '.join([str(i) for i in self.vendor.all()])

    def get_total_by_vendor(self, vendor_id: int) -> float:

        total_data = self.total_data
        data = total_data.get(str(vendor_id))
        subtotal = 0.00
        for subtotal_, tax_data in data.items():
            subtotal += float(subtotal_)
        return round(subtotal, 2)

    def __str__(self):
        return self.order_number


class OrderedFood(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='ordered_food')
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='customer_ordered_food')
    fooditem = models.ForeignKey(FoodItem, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    price = models.FloatField()
    amount = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.fooditem.food_title

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>FoodOnline</title>
	<!-- Google Font Family Link Start -->
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
	<!-- Google Font Family Link End -->

	<!-- CSS -->
	<link href="{% static 'css/iconmoon.css' %}" rel="stylesheet">
	<link href="{% static 'css/style.css' %}" rel="stylesheet">
	<link href="{% static 'css/cs-foodbakery-plugin.css' %}" rel="stylesheet">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
	<link href="{% static 'css/bootstrap-slider.css' %}" rel="stylesheet">
	<link href="{% static 'css/customs.css' %}" rel="stylesheet">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


	<!-- JAVASCRIPT -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	<script src="{% static 'js/modernizr.js' %}"></script>
	<script src="{% static 'js/bootstrap.js' %}"></script>

	<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

	<!-- Include the PayPal JavaScript SDK -->
    <script src="https://www.paypal.com/sdk/js?client-id={{PAYPAL_CLIENT_ID}}&currency=USD"></script>

	<link href="//cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css" rel="stylesheet">
	<script src="//cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
	<script>
		$(document).ready( function () {
    		$('#ordersTable').DataTable();
		} );
	</script>


	{% if '/' == request.path or 'profile' in request.path %}
		<script async
			src="https://maps.googleapis.com/maps/api/js?key={{GOOGLE_API_KEY}}&libraries=places&callback=initAutoComplete">
		</script>
	{% endif %}

	<script src="{% static 'js/custom.js' %}"></script>

	<style>
		body, .main-section p, .mce-content-body p{
			font:Normal  14px/24px "Open Sans", sans-serif;letter-spacing: 0px;text-transform: none;color: #515151 !important;
		}
	</style>
	    <style>

    </style>
</head>

<body>
	<!-- LOAD NAVBAR HERE -->
	{% include 'includes/navbar.html'%}
	<!-- LOAD CONTENT HERE -->
	{% block content %}
	<!-- CONTENT GOES HERE -->
	{% endblock %}
	<!-- LOAD FOOTER HERE -->
	{% include 'includes/footer.html'%}
</body>

templates/home.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

	{% include 'includes/alerts.html'%}

	<!--Main Wrapper-->
	<div class="wrapper">
		<!-- Main Section Start -->
		<div class="main-section">
			<!-- Home Pages Elements Strat -->
			<!-- Main Search Start -->
			<div class="page-section nopadding cs-nomargin"
				 style="padding-top: 200px; padding-bottom: 150px; margin-bottom: 0px; background: url(static/extra-images/bg-image1.jpg) no-repeat center / cover;">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
							<div class="element-title">
								<h1 style="font-size: 40px; color: #505050; text-transform: uppercase; line-height: 50px; margin-bottom: 25px; text-align:center;">
									We are in the business of food<br>our restaurants do</h1>
								<p style="font-size: 18px; letter-spacing: 1px; color: #505050; text-align:center;">
									Ridiculus sociosqu
									cursus neque cursus curae ante scelerisque vehicula.</p>
							</div>
						</div>
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
							<div class="main-search fancy bg-holder" style="border-radius: 6px;">
								<form action="{% url 'search'%}" method="get" style="margin-right: -76px">
									<div class="row">
										<div class="btn-group btn-group-toggle col-lg-2 col-md-2 col-sm-2 col-xs-12" data-toggle="buttons">
										    <label class="btn btn-light active"
												   style="height: 50px; padding-top: 13px; width: 0px;
												   border-top-left-radius: 6px; border-bottom-left-radius: 6px;
												   font-size: 16px;">
												<input type="radio" name="options" value="vendor" autocomplete="off" checked> Vendor
										    </label>
										    <label class="btn btn-light"
												   style="height: 50px; padding-top: 13px; width: 0px;
												   border-top-right-radius: 6px; border-bottom-right-radius: 6px;
												   font-size: 16px;">
												<input type="radio" name="options" value="fooditem" autocomplete="off"> Food
										    </label>
										</div>
										<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12" style="margin-left: -11px;">
											<div class="field-holder" style="border-radius: 6px;">
												<input type="text" name="keyword" placeholder="Resturant or food name">
											</div>
										</div>
										<div class="col-lg-4 col-md-4 col-sm-5 col-xs-12">
											<div class="field-holder">
												<ul>
													<li class="select-location">
														<div class="foodbakery-locations-fields-group foodbakery-focus-out" style="border-radius: 6px; margin-left: -11px;">
															<span class="foodbakery-search-location-icon" style="margin-left: -11px;"><i class="icon-location"></i></span>
															<input type="text" name="address" id="id_address" class="location-field-text filter" placeholder="All Locations" >
															<input type="hidden" name="lat" id="id_latitude" value="">
															<input type="hidden" name="long" id="id_longitude" value="">
														</div>
													</li>
												</ul>
											</div>
										</div>
										<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
											<select name="radius" id="radius" style="height: 50px; border-radius: 6px; margin-left: -11px;">
												<option value="100" selected >Choose radius</option>
												<option value="1">1km</option>
												<option value="2">2km</option>
												<option value="5">5km</option>
												<option value="10">10km</option>
												<option value="15">15km</option>
												<option value="30">30km</option>
												<option value="50">50km</option>
												<option value="100">100km</option>
											</select>
										</div>
										<div class="col-lg-1 col-md-1 col-sm-1 col-xs-12">
											<div class="field-holder">
												<button type="submit" class="btn btn-success" style="font-size: 25px; border-radius: 6px; margin-left: -21px;">
													<i class="bi bi-search"></i>
                                        		</button>
											</div>
										</div>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- Main Search End -->
			<!-- Top Restarurants Section Start -->
			<div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 0px;margin-bottom: 0px;background: #ffffff;">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="element-title align-left">
								<h2>Top Restaurants</h2>
								<p>Explore restaurants, bars, and cafés by locality</p>
							</div>
						</div>
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" style="padding-right: 0 !important; padding-left: 0 !important;">
							<div class="company-logo">
								<ul>
									{% for vendor in vendors %}
										<li>
											<figure>
												<a href="{% url 'vendor-detail' vendor.vendor_slug %}">
													<img style="border-radius: 10px;" src="{{ vendor.user_profile.profile_picture.url }}" class="img-list wp-post-image" alt="">
												</a>
											</figure>
										</li>
									{% endfor %}
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- Top Restarurants Section End -->
			<!-- Choose From Most Popular Listin Start -->
			<div class="page-section nopadding cs-nomargin" style="margin-top: 0px;padding-top: 60px;padding-bottom: 50px;margin-bottom: 0px;background: #ffffff;">
				<div class="container">
					<div class="row">
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="element-title align-center">
								<h2>Choose From Most Popular Restaurants</h2>
								<p>Cum doctus civibus efficiantur in imperdiet deterruisset.</p>
							</div>
						</div>
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="listing fancy">
								<ul class="row">
									{% for vendor in top_vendors %}
										<li class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
											<div class="list-post featured">
												<div class="img-holder">
													<figure>
														<img style="border-radius: 10px;" src="{{ vendor.user_profile.profile_picture.url }}" class="img-list wp-post-image" alt="">
													</figure>
													{% if vendor.is_open %}
														<span class="restaurant-status open">
															<em class="bookmarkRibbon"></em>Open
														</span>
													{% else %}
														<span class="restaurant-status close">
															<em class="bookmarkRibbon"></em>Closed
														</span>
													{% endif %}
												</div>
												<div class="text-holder">
													<div class="post-title">
														<h5>
															<a href="{% url 'vendor-detail' vendor.vendor_slug %}">{{vendor.vendor_name}}</a>
														</h5>
													</div>
													{% if vendor.user_profile.city and vendor.user_profile.state and vendor.user_profile.pin_code %}
														<span> {{vendor.user_profile.city}}, {{vendor.user_profile.state}}, {{vendor.user_profile.pin_code}} </span>
													{% endif %}
													{% if vendor.kms %}
														<br>
														<span><small><b>{{vendor.kms}} km </b>away</small></span>
													{% endif %}
												</div>
											</div>
										</li>
									{% endfor %}
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}